# Generated by Django 5.2.5 on 2025-08-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='updated_at',
            new_name='actualizado_el',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='created_at',
            new_name='creado_el',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='salas.sala')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['sala', 'fecha'], name='salas_reser_sala_id_ab3ae7_idx')],
            },
        ),
    ]
